# Generated by Django 5.0.3 on 2024-04-01 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                null=True, related_name="tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
