# Generated by Django 5.0.3 on 2024-04-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "project")},
        ),
        migrations.AlterIndexTogether(
            name="tag",
            index_together={("name", "project")},
        ),
    ]
