# Generated by Django 5.0.3 on 2024-04-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_task_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-updated_at"]},
        ),
    ]
